-   id: prefix-issue
    name: Prefix Issue
    description: "Prefixes the commit with the issue number"
    entry: prefix-issue
    language: node
    types: [node]
    args: [-i]
    # for backward compatibility
    files: ''
    minimum_pre_commit_version: 0.15.0